/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ComplaintStatus = IDL.Variant({
  'Open' : IDL.Null,
  'InProgress' : IDL.Null,
  'Resolved' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const ComplaintCategory = IDL.Variant({
  'Noise' : IDL.Null,
  'Safety' : IDL.Null,
  'Maintenance' : IDL.Null,
  'Cleanliness' : IDL.Null,
  'Other' : IDL.Null,
});
export const ComplaintPriority = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
});
export const Complaint = IDL.Record({
  'id' : IDL.Nat,
  'status' : ComplaintStatus,
  'title' : IDL.Text,
  'apartmentId' : IDL.Nat,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'tenantPrincipal' : IDL.Principal,
  'resolutionNotes' : IDL.Opt(IDL.Text),
  'updatedAt' : Timestamp,
  'category' : ComplaintCategory,
  'priority' : ComplaintPriority,
  'resolvedAt' : IDL.Opt(Timestamp),
});
export const Apartment = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'hostPrincipal' : IDL.Principal,
  'address' : IDL.Text,
});
export const UserRole = IDL.Variant({ 'Tenant' : IDL.Null, 'Host' : IDL.Null });
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'apartmentId' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
});

export const idlService = IDL.Service({
  'createApartment' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'deleteComplaint' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getAllComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
  'getApartmentComplaints' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Complaint)],
      ['query'],
    ),
  'getApartments' : IDL.Func([], [IDL.Vec(Apartment)], ['query']),
  'getComplaint' : IDL.Func([IDL.Nat], [IDL.Opt(Complaint)], ['query']),
  'getComplaintStats' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'resolved' : IDL.Nat,
          'total' : IDL.Nat,
          'open' : IDL.Nat,
          'inProgress' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getComplaintsByCategory' : IDL.Func(
      [ComplaintCategory],
      [IDL.Vec(Complaint)],
      ['query'],
    ),
  'getComplaintsByStatus' : IDL.Func(
      [ComplaintStatus],
      [IDL.Vec(Complaint)],
      ['query'],
    ),
  'getMyApartments' : IDL.Func([], [IDL.Vec(Apartment)], ['query']),
  'getMyComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'postComplaint' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, ComplaintCategory, ComplaintPriority],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'registerAsHost' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'registerAsTenant' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateComplaintStatus' : IDL.Func(
      [IDL.Nat, ComplaintStatus, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ComplaintStatus = IDL.Variant({
    'Open' : IDL.Null,
    'InProgress' : IDL.Null,
    'Resolved' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const ComplaintCategory = IDL.Variant({
    'Noise' : IDL.Null,
    'Safety' : IDL.Null,
    'Maintenance' : IDL.Null,
    'Cleanliness' : IDL.Null,
    'Other' : IDL.Null,
  });
  const ComplaintPriority = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const Complaint = IDL.Record({
    'id' : IDL.Nat,
    'status' : ComplaintStatus,
    'title' : IDL.Text,
    'apartmentId' : IDL.Nat,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'tenantPrincipal' : IDL.Principal,
    'resolutionNotes' : IDL.Opt(IDL.Text),
    'updatedAt' : Timestamp,
    'category' : ComplaintCategory,
    'priority' : ComplaintPriority,
    'resolvedAt' : IDL.Opt(Timestamp),
  });
  const Apartment = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'hostPrincipal' : IDL.Principal,
    'address' : IDL.Text,
  });
  const UserRole = IDL.Variant({ 'Tenant' : IDL.Null, 'Host' : IDL.Null });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'apartmentId' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
  });
  
  return IDL.Service({
    'createApartment' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'deleteComplaint' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getAllComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
    'getApartmentComplaints' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Complaint)],
        ['query'],
      ),
    'getApartments' : IDL.Func([], [IDL.Vec(Apartment)], ['query']),
    'getComplaint' : IDL.Func([IDL.Nat], [IDL.Opt(Complaint)], ['query']),
    'getComplaintStats' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'resolved' : IDL.Nat,
            'total' : IDL.Nat,
            'open' : IDL.Nat,
            'inProgress' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getComplaintsByCategory' : IDL.Func(
        [ComplaintCategory],
        [IDL.Vec(Complaint)],
        ['query'],
      ),
    'getComplaintsByStatus' : IDL.Func(
        [ComplaintStatus],
        [IDL.Vec(Complaint)],
        ['query'],
      ),
    'getMyApartments' : IDL.Func([], [IDL.Vec(Apartment)], ['query']),
    'getMyComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'postComplaint' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, ComplaintCategory, ComplaintPriority],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'registerAsHost' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'registerAsTenant' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateComplaintStatus' : IDL.Func(
        [IDL.Nat, ComplaintStatus, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };