/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Apartment {
  'id' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'hostPrincipal' : Principal,
  'address' : string,
}
export interface Complaint {
  'id' : bigint,
  'status' : ComplaintStatus,
  'title' : string,
  'apartmentId' : bigint,
  'createdAt' : Timestamp,
  'description' : string,
  'tenantPrincipal' : Principal,
  'resolutionNotes' : [] | [string],
  'updatedAt' : Timestamp,
  'category' : ComplaintCategory,
  'priority' : ComplaintPriority,
  'resolvedAt' : [] | [Timestamp],
}
export type ComplaintCategory = { 'Noise' : null } |
  { 'Safety' : null } |
  { 'Maintenance' : null } |
  { 'Cleanliness' : null } |
  { 'Other' : null };
export type ComplaintPriority = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null };
export type ComplaintStatus = { 'Open' : null } |
  { 'InProgress' : null } |
  { 'Resolved' : null };
export type Timestamp = bigint;
export interface UserProfile {
  'principal' : Principal,
  'apartmentId' : [] | [bigint],
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
}
export type UserRole = { 'Tenant' : null } |
  { 'Host' : null };
export interface _SERVICE {
  'createApartment' : ActorMethod<
    [string, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'deleteComplaint' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getAllComplaints' : ActorMethod<[], Array<Complaint>>,
  'getApartmentComplaints' : ActorMethod<[bigint], Array<Complaint>>,
  'getApartments' : ActorMethod<[], Array<Apartment>>,
  'getComplaint' : ActorMethod<[bigint], [] | [Complaint]>,
  'getComplaintStats' : ActorMethod<
    [bigint],
    {
      'resolved' : bigint,
      'total' : bigint,
      'open' : bigint,
      'inProgress' : bigint,
    }
  >,
  'getComplaintsByCategory' : ActorMethod<
    [ComplaintCategory],
    Array<Complaint>
  >,
  'getComplaintsByStatus' : ActorMethod<[ComplaintStatus], Array<Complaint>>,
  'getMyApartments' : ActorMethod<[], Array<Apartment>>,
  'getMyComplaints' : ActorMethod<[], Array<Complaint>>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'isRegistered' : ActorMethod<[], boolean>,
  'postComplaint' : ActorMethod<
    [bigint, string, string, ComplaintCategory, ComplaintPriority],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'registerAsHost' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'registerAsTenant' : ActorMethod<
    [string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateComplaintStatus' : ActorMethod<
    [bigint, ComplaintStatus, [] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];