/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface Complaint {
    id: bigint;
    status: ComplaintStatus;
    title: string;
    apartmentId: bigint;
    createdAt: Timestamp;
    description: string;
    tenantPrincipal: Principal;
    resolutionNotes?: string;
    updatedAt: Timestamp;
    category: ComplaintCategory;
    priority: ComplaintPriority;
    resolvedAt?: Timestamp;
}
export interface Apartment {
    id: bigint;
    name: string;
    createdAt: Timestamp;
    hostPrincipal: Principal;
    address: string;
}
export interface UserProfile {
    principal: Principal;
    apartmentId?: bigint;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
}
export enum ComplaintCategory {
    Noise = "Noise",
    Safety = "Safety",
    Maintenance = "Maintenance",
    Cleanliness = "Cleanliness",
    Other = "Other"
}
export enum ComplaintPriority {
    Low = "Low",
    High = "High",
    Medium = "Medium"
}
export enum ComplaintStatus {
    Open = "Open",
    InProgress = "InProgress",
    Resolved = "Resolved"
}
export enum UserRole {
    Tenant = "Tenant",
    Host = "Host"
}
export interface backendInterface {
    createApartment(name: string, address: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteComplaint(id: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getAllComplaints(): Promise<Array<Complaint>>;
    getApartmentComplaints(apartmentId: bigint): Promise<Array<Complaint>>;
    getApartments(): Promise<Array<Apartment>>;
    getComplaint(id: bigint): Promise<Complaint | null>;
    getComplaintStats(apartmentId: bigint): Promise<{
        resolved: bigint;
        total: bigint;
        open: bigint;
        inProgress: bigint;
    }>;
    getComplaintsByCategory(category: ComplaintCategory): Promise<Array<Complaint>>;
    getComplaintsByStatus(status: ComplaintStatus): Promise<Array<Complaint>>;
    getMyApartments(): Promise<Array<Apartment>>;
    getMyComplaints(): Promise<Array<Complaint>>;
    getUserProfile(): Promise<UserProfile | null>;
    isRegistered(): Promise<boolean>;
    postComplaint(apartmentId: bigint, title: string, description: string, category: ComplaintCategory, priority: ComplaintPriority): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    registerAsHost(name: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    registerAsTenant(name: string, apartmentId: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateComplaintStatus(id: bigint, status: ComplaintStatus, resolutionNotes: string | null): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { Complaint as _Complaint, ComplaintCategory as _ComplaintCategory, ComplaintPriority as _ComplaintPriority, ComplaintStatus as _ComplaintStatus, Timestamp as _Timestamp, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createApartment(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createApartment(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createApartment(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteComplaint(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComplaint(arg0);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComplaint(arg0);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllComplaints(): Promise<Array<Complaint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllComplaints();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllComplaints();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApartmentComplaints(arg0: bigint): Promise<Array<Complaint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApartmentComplaints(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApartmentComplaints(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApartments(): Promise<Array<Apartment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApartments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApartments();
            return result;
        }
    }
    async getComplaint(arg0: bigint): Promise<Complaint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getComplaint(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComplaint(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComplaintStats(arg0: bigint): Promise<{
        resolved: bigint;
        total: bigint;
        open: bigint;
        inProgress: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getComplaintStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComplaintStats(arg0);
            return result;
        }
    }
    async getComplaintsByCategory(arg0: ComplaintCategory): Promise<Array<Complaint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComplaintsByCategory(to_candid_ComplaintCategory_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComplaintsByCategory(to_candid_ComplaintCategory_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComplaintsByStatus(arg0: ComplaintStatus): Promise<Array<Complaint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComplaintsByStatus(to_candid_ComplaintStatus_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComplaintsByStatus(to_candid_ComplaintStatus_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyApartments(): Promise<Array<Apartment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyApartments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyApartments();
            return result;
        }
    }
    async getMyComplaints(): Promise<Array<Complaint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyComplaints();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyComplaints();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async isRegistered(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isRegistered();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isRegistered();
            return result;
        }
    }
    async postComplaint(arg0: bigint, arg1: string, arg2: string, arg3: ComplaintCategory, arg4: ComplaintPriority): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.postComplaint(arg0, arg1, arg2, to_candid_ComplaintCategory_n15(this._uploadFile, this._downloadFile, arg3), to_candid_ComplaintPriority_n25(this._uploadFile, this._downloadFile, arg4));
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postComplaint(arg0, arg1, arg2, to_candid_ComplaintCategory_n15(this._uploadFile, this._downloadFile, arg3), to_candid_ComplaintPriority_n25(this._uploadFile, this._downloadFile, arg4));
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerAsHost(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerAsHost(arg0);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerAsHost(arg0);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerAsTenant(arg0: string, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerAsTenant(arg0, arg1);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerAsTenant(arg0, arg1);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateComplaintStatus(arg0: bigint, arg1: ComplaintStatus, arg2: string | null): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateComplaintStatus(arg0, to_candid_ComplaintStatus_n17(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n27(this._uploadFile, this._downloadFile, arg2));
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateComplaintStatus(arg0, to_candid_ComplaintStatus_n17(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n27(this._uploadFile, this._downloadFile, arg2));
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ComplaintCategory_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ComplaintCategory): ComplaintCategory {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_ComplaintPriority_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ComplaintPriority): ComplaintPriority {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ComplaintStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ComplaintStatus): ComplaintStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Complaint_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Complaint): Complaint {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Complaint]): Complaint | null {
    return value.length === 0 ? null : from_candid_Complaint_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    apartmentId: [] | [bigint];
    name: string;
    createdAt: _Timestamp;
    role: _UserRole;
}): {
    principal: Principal;
    apartmentId?: bigint;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
} {
    return {
        principal: value.principal,
        apartmentId: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.apartmentId)),
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n23(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ComplaintStatus;
    title: string;
    apartmentId: bigint;
    createdAt: _Timestamp;
    description: string;
    tenantPrincipal: Principal;
    resolutionNotes: [] | [string];
    updatedAt: _Timestamp;
    category: _ComplaintCategory;
    priority: _ComplaintPriority;
    resolvedAt: [] | [_Timestamp];
}): {
    id: bigint;
    status: ComplaintStatus;
    title: string;
    apartmentId: bigint;
    createdAt: Timestamp;
    description: string;
    tenantPrincipal: Principal;
    resolutionNotes?: string;
    updatedAt: Timestamp;
    category: ComplaintCategory;
    priority: ComplaintPriority;
    resolvedAt?: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_ComplaintStatus_n6(_uploadFile, _downloadFile, value.status),
        title: value.title,
        apartmentId: value.apartmentId,
        createdAt: value.createdAt,
        description: value.description,
        tenantPrincipal: value.tenantPrincipal,
        resolutionNotes: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.resolutionNotes)),
        updatedAt: value.updatedAt,
        category: from_candid_ComplaintCategory_n9(_uploadFile, _downloadFile, value.category),
        priority: from_candid_ComplaintPriority_n11(_uploadFile, _downloadFile, value.priority),
        resolvedAt: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.resolvedAt))
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Noise: null;
} | {
    Safety: null;
} | {
    Maintenance: null;
} | {
    Cleanliness: null;
} | {
    Other: null;
}): ComplaintCategory {
    return "Noise" in value ? ComplaintCategory.Noise : "Safety" in value ? ComplaintCategory.Safety : "Maintenance" in value ? ComplaintCategory.Maintenance : "Cleanliness" in value ? ComplaintCategory.Cleanliness : "Other" in value ? ComplaintCategory.Other : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
}): ComplaintPriority {
    return "Low" in value ? ComplaintPriority.Low : "High" in value ? ComplaintPriority.High : "Medium" in value ? ComplaintPriority.Medium : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Tenant: null;
} | {
    Host: null;
}): UserRole {
    return "Tenant" in value ? UserRole.Tenant : "Host" in value ? UserRole.Host : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Open: null;
} | {
    InProgress: null;
} | {
    Resolved: null;
}): ComplaintStatus {
    return "Open" in value ? ComplaintStatus.Open : "InProgress" in value ? ComplaintStatus.InProgress : "Resolved" in value ? ComplaintStatus.Resolved : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Complaint>): Array<Complaint> {
    return value.map((x)=>from_candid_Complaint_n4(_uploadFile, _downloadFile, x));
}
function to_candid_ComplaintCategory_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ComplaintCategory): _ComplaintCategory {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_ComplaintPriority_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ComplaintPriority): _ComplaintPriority {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_ComplaintStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ComplaintStatus): _ComplaintStatus {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ComplaintCategory): {
    Noise: null;
} | {
    Safety: null;
} | {
    Maintenance: null;
} | {
    Cleanliness: null;
} | {
    Other: null;
} {
    return value == ComplaintCategory.Noise ? {
        Noise: null
    } : value == ComplaintCategory.Safety ? {
        Safety: null
    } : value == ComplaintCategory.Maintenance ? {
        Maintenance: null
    } : value == ComplaintCategory.Cleanliness ? {
        Cleanliness: null
    } : value == ComplaintCategory.Other ? {
        Other: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ComplaintStatus): {
    Open: null;
} | {
    InProgress: null;
} | {
    Resolved: null;
} {
    return value == ComplaintStatus.Open ? {
        Open: null
    } : value == ComplaintStatus.InProgress ? {
        InProgress: null
    } : value == ComplaintStatus.Resolved ? {
        Resolved: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ComplaintPriority): {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
} {
    return value == ComplaintPriority.Low ? {
        Low: null
    } : value == ComplaintPriority.High ? {
        High: null
    } : value == ComplaintPriority.Medium ? {
        Medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
